### ISSUE TITLE
Better naming for the proxy

### ISSUE THREAD

**Issue by b00f** [nagarajmanjunath/zarb-explorer#2]
As I checked the proxy, you have a [function name](https://github.com/nagarajmanjunath/zarb-explorer/blob/b0160d26e288561c23035dc538f3d98ec13ec327/src/proxy/proxy.jsx#L13) that look to be not matched with its behavior. You may replace it with:
```
function BlockchainInfo() { // Not `GetBlockInfo`
  return BlockchainInfo();
}
```

**Comment by nagarajmanjunath** [comment]
change the naming in proxy
